### ISSUE TITLE
v4.6 changes where exports are stored

### ISSUE THREAD

**Issue by ZenerDeveloper** [SmartPack/PackageManager#23] opened 2021-06-14 17:42 UTC
In v4.5, exported apks are stored in `/storage/emulated/user/Package_Manager/` but in v4.6 it now stores it in `/storage/emulated/user/Android/data/com.smartpack.packagemanager/files/` Which is a lot more difficult to get to, with samsung files showing nothing in the data folder entirely, and material files needing ti get access thriugh documentsui.
It eould be nice to have the option of customizing where it stores the exports in settings, but it seems unnecessarily difficult to access the exports, and if you uninstall the app they get deleted.

**Comment by sunilpaulmathew** [comment] 2021-06-14 21:36
@ZenerDeveloper 
Thanks to Google for their policy changes for Android 11, I'm forced to do it. The new path is one of the place in which app can freely access. In order to access /sdcard/PackaManager in Android 11, "All files permission" should be granted. The only thing I can do is to store files in the old path once the users provided the permission. However, many users may not give it due to privacy concerns. Btw, the issue is not only applicable to Samsung file manager, but every one on Android 11.

**Comment by sunilpaulmathew** [comment] 2021-06-15 18:23
Should be fixed with the next update if users grant "All files permission" to the app. So, closing this issue.

**Closed by sunilpaulmathew** 2021-06-15 18:23 UTC
