### ISSUE TITLE
crashes when tapping uninstalled app

### ISSUE THREAD

**Issue by shalva97** [SmartPack/PackageManager#21] opened 2021-05-06 13:00 UTC
1. click an app
2. press uninstall icon, and agree to uninstall it
3. go back to the list
4. uninstalled app is still there
5. click on it and app crashes

```
2021-05-06 16:57:21.705 25655-25655/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartpack.packagemanager, PID: 25655
    java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at b.b.a.b.a.x(:2)
        at b.c.a.b.b.onClick(:10)
        at android.view.View.performClick(View.java:6597)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25906)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 ```

**Comment by sunilpaulmathew** [comment] 2021-05-07 10:12
@shalva97 
That is really strange. I can't reproduce that issue here. It shows a snackbar with the following content "**Selected package is just removed! Aborting…**"

**Comment by shalva97** [comment] 2021-05-08 16:20
it should be removed from the list if it is uninstalled... at least thats what I expect to happen, the list should be updated when I return to it

**Comment by sunilpaulmathew** [comment] 2021-07-22 20:43
I'm closing this issue since it is already addressed in a recent update. Feel free to reopen this issue if you're not satisfied.

**Closed by sunilpaulmathew** 2021-07-22 20:43 UTC
