### ISSUE TITLE
Unable to open mi file manager app in package manager. 

### ISSUE THREAD

**Issue by pokegamer5547** [SmartPack/PackageManager#18] opened 2021-04-02 02:33 UTC
Package manager doesn't show the settings and show an error when I click on mi file manager app of Xiaomi even tho it is installed already on system and loading up fine when I launch it from launcher. 
![Screenshot_2021-04-02-08-00-17-215_com smartpack packagemanager](https://user-images.githubusercontent.com/65234485/113374004-b2881f00-9389-11eb-80a3-e2202c3d6745.jpg)
![Screenshot_2021-04-02-08-00-23-649_com mi android globalFileexplorer](https://user-images.githubusercontent.com/65234485/113374031-c469c200-9389-11eb-9b7a-717bc5d40fbf.jpg)

**Comment by sunilpaulmathew** [comment] 2021-04-02 08:34
@pokegamer5547 
You mean, when you click on it, it doesn't load the "**App Info**" page at all?

**Comment by pokegamer5547** [comment] 2021-04-02 08:41
> @pokegamer5547
> You mean, when you click on it, it doesn't load the "**App Info**" page at all?

Yes that's right. It doesn't happen when I click on other apps.

**Comment by sunilpaulmathew** [comment] 2021-04-02 10:19
> > @pokegamer5547
> > You mean, when you click on it, it doesn't load the "**App Info**" page at all?
> 
> Yes that's right. It doesn't happen when I click on other apps.

Strange. Is that app available in Google Play or somewhere else so that I will try to reproduce here?

**Comment by pokegamer5547** [comment] 2021-04-02 11:19
> > > @pokegamer5547
> > > You mean, when you click on it, it doesn't load the "**App Info**" page at all?
> > 
> > 
> > Yes that's right. It doesn't happen when I click on other apps.
> 
> Strange. Is that app available in Google Play or somewhere else so that I will try to reproduce here?

Yes mi file manager is available on Google Play Store. Its an system app in my phone though. Link; https://play.google.com/store/apps/details?id=com.mi.android.globalFileexplorer

**Comment by sunilpaulmathew** [comment] 2021-04-03 08:12
> might fix it but it di

The strange thing is that it worked fine on my testing.

**Comment by pokegamer5547** [comment] 2021-04-03 08:23
> > might fix it but it di
> 
> The strange thing is that it worked fine on my testing.

Really? Well this is really strange bug.i don't know why it's happening only in my phone.i have even tried clearing it's data but it's still happening. Is there any way available to provide log in package manager?

**Comment by ZenerDeveloper** [comment] 2021-07-03 23:51
I believe this may be related to my issue #24 as mi file manager has the package name `com.mi.android.globalFileexplorer`
Try reopening the app and finding it in that list (never searching anything up before) or searching something not in the package name for example `file manager`
Also @sunilpaulmathew try tapping it after searching `file` to see if that reproduces the issue.

**Comment by sunilpaulmathew** [comment] 2021-07-04 08:33
> I believe this may be related to my issue #24 as mi file manager has the package name `com.mi.android.globalFileexplorer`
> Try reopening the app and finding it in that list (never searching anything up before) or searching something not in the package name for example `file manager`
> Also @sunilpaulmathew try tapping it after searching `file` to see if that reproduces the issue.

You're perfectly correct. I know why it happened in the current implementation of app. I'm looking for an alternate method that completely avoid case sensitivity. Suggestions are welcome. Thanks

**Comment by sunilpaulmathew** [comment] 2021-07-22 20:46
I'm closing this issue since it is already addressed in a recent update. Feel free to reopen this issue if you're not satisfied.

**Closed by sunilpaulmathew** 2021-07-22 20:46 UTC
